[supervisord]
nodaemon=true
user=testmesh
logfile=/dev/stdout
logfile_maxbytes=0

[program:api]
command=/app/api/testmesh-api
directory=/app/api
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:dashboard]
command=node /app/dashboard/server.js
directory=/app/dashboard
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
