apiVersion: apps/v1
kind: Deployment
metadata:
  name: testmesh-api
spec:
  template:
    spec:
      containers:
        - name: api
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testmesh-dashboard
spec:
  template:
    spec:
      containers:
        - name: dashboard
          resources:
            requests:
              memory: "64Mi"
              cpu: "25m"
            limits:
              memory: "256Mi"
              cpu: "250m"
