// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/recommendation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_proto_recommendation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommendation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_proto_recommendation_proto_rawDescGZIP(), []int{0}
}

func (x *UserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductRequest) Reset() {
	*x = ProductRequest{}
	mi := &file_proto_recommendation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductRequest) ProtoMessage() {}

func (x *ProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommendation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductRequest.ProtoReflect.Descriptor instead.
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_recommendation_proto_rawDescGZIP(), []int{1}
}

func (x *ProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ProductList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductIds    []string               `protobuf:"bytes,1,rep,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductList) Reset() {
	*x = ProductList{}
	mi := &file_proto_recommendation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductList) ProtoMessage() {}

func (x *ProductList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommendation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductList.ProtoReflect.Descriptor instead.
func (*ProductList) Descriptor() ([]byte, []int) {
	return file_proto_recommendation_proto_rawDescGZIP(), []int{2}
}

func (x *ProductList) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

var File_proto_recommendation_proto protoreflect.FileDescriptor

const file_proto_recommendation_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/recommendation.proto\x12\x0erecommendation\"<\n" +
	"\vUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"E\n" +
	"\x0eProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\".\n" +
	"\vProductList\x12\x1f\n" +
	"\vproduct_ids\x18\x01 \x03(\tR\n" +
	"productIds2\xba\x01\n" +
	"\x15RecommendationService\x12N\n" +
	"\x12GetRecommendations\x12\x1b.recommendation.UserRequest\x1a\x1b.recommendation.ProductList\x12Q\n" +
	"\x12GetSimilarProducts\x12\x1e.recommendation.ProductRequest\x1a\x1b.recommendation.ProductListB\x1eZ\x1crecommendation-service/protob\x06proto3"

var (
	file_proto_recommendation_proto_rawDescOnce sync.Once
	file_proto_recommendation_proto_rawDescData []byte
)

func file_proto_recommendation_proto_rawDescGZIP() []byte {
	file_proto_recommendation_proto_rawDescOnce.Do(func() {
		file_proto_recommendation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_recommendation_proto_rawDesc), len(file_proto_recommendation_proto_rawDesc)))
	})
	return file_proto_recommendation_proto_rawDescData
}

var file_proto_recommendation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_recommendation_proto_goTypes = []any{
	(*UserRequest)(nil),    // 0: recommendation.UserRequest
	(*ProductRequest)(nil), // 1: recommendation.ProductRequest
	(*ProductList)(nil),    // 2: recommendation.ProductList
}
var file_proto_recommendation_proto_depIdxs = []int32{
	0, // 0: recommendation.RecommendationService.GetRecommendations:input_type -> recommendation.UserRequest
	1, // 1: recommendation.RecommendationService.GetSimilarProducts:input_type -> recommendation.ProductRequest
	2, // 2: recommendation.RecommendationService.GetRecommendations:output_type -> recommendation.ProductList
	2, // 3: recommendation.RecommendationService.GetSimilarProducts:output_type -> recommendation.ProductList
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_recommendation_proto_init() }
func file_proto_recommendation_proto_init() {
	if File_proto_recommendation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_recommendation_proto_rawDesc), len(file_proto_recommendation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_recommendation_proto_goTypes,
		DependencyIndexes: file_proto_recommendation_proto_depIdxs,
		MessageInfos:      file_proto_recommendation_proto_msgTypes,
	}.Build()
	File_proto_recommendation_proto = out.File
	file_proto_recommendation_proto_goTypes = nil
	file_proto_recommendation_proto_depIdxs = nil
}
