environment: development

server:
  port: 5016
  read_timeout: 15s
  write_timeout: 15s

database:
  host: localhost
  port: 5432
  user: root
  password: admin
  dbname: testmesh
  sslmode: disable
  max_conns: 25
  max_idle: 5

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

neo4j:
  uri: bolt://localhost:7687
  user: neo4j
  password: testmesh
  database: neo4j

graph:
  enabled: true

logger:
  level: info
  output_path: stdout
